"""A plan's row universe, computed once before grouping
(docs/keyspace_phase_plan.md).

A REGION is one kind of row the plan can return: the set of requested entity
keys present on it. Customers and orders, `orders.customer_id: ~customer_id`,
`select customer_id, status`: `{customer, order}` and `{customer}`.

Regions are generated by SOURCES. A row of a datasource carries every key the
datasource binds plus whatever a keyed lookup from those reaches, and each
carried key remembers the `~` bindings on its path (its CAUSE): an empty cause
means the rows span the key's whole domain. A source whose carried keys cover
only some of the requested entities witnesses a smaller region, which survives
only when every larger source reaches its rows through a `~`; those `~` keys
are the region's spans. Two sources carrying the same entities are one region
(`returns` binding `~order_id, ~item_id` beside `lines`), and there is no
`{user, product}` cell because no source carries exactly that.

Not modelled yet: a lookup through a source whose own grain is bound `~` (it
may miss, which makes the looked-up entity optional on the row), `complete
where` partitions (the union machinery owns them), and regions only a JOIN of
two facts can witness (the base region stands in for them).
"""

from __future__ import annotations

from dataclasses import dataclass
from functools import partial
from weakref import ReferenceType, ref

from trilogy.core.enums import Purpose
from trilogy.core.models.build import (
    BuildConcept,
    BuildDatasource,
    BuildWhereClause,
)
from trilogy.core.models.build_environment import BuildEnvironment
from trilogy.core.processing.condition_utility import condition_proves_non_null

from .models import ConceptAttrs, Keyspace, Region

# key -> the `~` bindings between a source's rows and that key's whole domain
Carried = dict[str, frozenset[str]]


@dataclass(frozen=True)
class _SourceFacts:
    identifier: str
    grain: frozenset[str]
    grain_is_partial: bool
    # bound address -> ({address} when bound `~`, else empty)
    bound: Carried


@dataclass
class _ModelFacts:
    """Binding facts of one environment, canonicalized over pseudonyms."""

    stamp: tuple[int, ...]
    canonical: dict[str, str]
    sources: tuple[_SourceFacts, ...]
    carried: dict[str, Carried]


_FACTS_CACHE: dict[int, tuple[ReferenceType[BuildEnvironment], _ModelFacts]] = {}


def _evict_facts(key: int, _dead: ReferenceType) -> None:
    _FACTS_CACHE.pop(key, None)


def _build_datasources(environment: BuildEnvironment) -> list[BuildDatasource]:
    return [
        ds for ds in environment.datasources.values() if isinstance(ds, BuildDatasource)
    ]


def _canonical_addresses(environment: BuildEnvironment) -> dict[str, str]:
    """address -> the smallest spelling among it and its pseudonyms."""
    classes: dict[str, set[str]] = {}
    for key, concept in environment.concepts.items():
        merged = {key, concept.address, *concept.pseudonyms}
        for member in list(merged):
            merged |= classes.get(member, set())
        for member in merged:
            classes[member] = merged
    return {address: min(members) for address, members in classes.items()}


def _better(new: frozenset[str], old: frozenset[str] | None) -> bool:
    return old is None or len(new) < len(old)


def _source_facts(ds: BuildDatasource, canonical: dict[str, str]) -> _SourceFacts:
    partial_addresses = ds.column_level_partial_addresses
    bound: Carried = {}
    for column in ds.columns:
        address = column.concept.address
        key = canonical.get(address, address)
        cause = frozenset({key}) if address in partial_addresses else frozenset()
        if _better(cause, bound.get(key)):
            bound[key] = cause
    grain = (
        frozenset()
        if ds.grain.abstract
        else frozenset(canonical.get(g, g) for g in ds.grain.components)
    )
    return _SourceFacts(
        identifier=ds.identifier,
        grain=grain,
        grain_is_partial=any(bound.get(g) for g in grain),
        bound=bound,
    )


def _carried(anchor: _SourceFacts, sources: tuple[_SourceFacts, ...]) -> Carried:
    """Every address a row of `anchor` has a value for, by keyed lookup.

    A lookup enters a source only through its whole grain, and never one whose
    grain is bound `~`: that source may hold no row for the anchor's key."""
    carried = dict(anchor.bound)
    changed = True
    while changed:
        changed = False
        for other in sources:
            if other is anchor or not other.grain or other.grain_is_partial:
                continue
            if not other.grain <= carried.keys():
                continue
            path: frozenset[str] = frozenset().union(*(carried[g] for g in other.grain))
            for address, cause in other.bound.items():
                if _better(path | cause, carried.get(address)):
                    carried[address] = path | cause
                    changed = True
    return carried


def _model_facts(environment: BuildEnvironment) -> _ModelFacts:
    datasources = _build_datasources(environment)
    # pin-heal and partition exclusion swap datasources in place before planning
    stamp = tuple(id(ds) for ds in datasources)
    cache_key = id(environment)
    cached = _FACTS_CACHE.get(cache_key)
    if cached is not None and cached[0]() is environment and cached[1].stamp == stamp:
        return cached[1]
    canonical = _canonical_addresses(environment)
    sources = tuple(_source_facts(ds, canonical) for ds in datasources)
    facts = _ModelFacts(
        stamp=stamp,
        canonical=canonical,
        sources=sources,
        carried={s.identifier: _carried(s, sources) for s in sources},
    )
    _FACTS_CACHE[cache_key] = (
        ref(environment, partial(_evict_facts, cache_key)),
        facts,
    )
    return facts


def _entity_keys(
    address: str,
    declared: dict[str, tuple[Purpose, frozenset[str]]],
    environment: BuildEnvironment,
    seen: frozenset[str] = frozenset(),
) -> frozenset[str]:
    """The entity keys a concept is a function of. A key is its own entity:
    the `keys` it carries are an FK-path addressing artifact (`customer_id`
    bound on `orders` lists `order_id`), not a determinant. Anything else lives
    on its keys' entities: an aggregate `by status` is keyed on the order."""
    known = declared.get(address)
    if known is None:
        concept = environment.concepts.get(address)
        if concept is None:
            return frozenset()
        known = (concept.purpose, frozenset(concept.keys or ()))
    purpose, keys = known
    if purpose == Purpose.KEY:
        return frozenset({address})
    seen = seen | {address}
    return frozenset().union(
        *(_entity_keys(k, declared, environment, seen) for k in keys if k not in seen)
    )


def _identifying_keys(source: _SourceFacts, present: frozenset[str]) -> frozenset[str]:
    """What identifies `source`'s rows once projected onto `present`: its grain
    when the projection keeps it, else every projected key."""
    if source.grain and source.grain <= present:
        return source.grain
    return present


def _extension_regions(
    entities: frozenset[str], facts: _ModelFacts
) -> dict[frozenset[str], tuple[set[str], set[str]]]:
    """present -> (spans, witnessing sources) for each proper sub-region."""
    projected = {
        s.identifier: frozenset(facts.carried[s.identifier].keys() & entities)
        for s in facts.sources
    }
    out: dict[frozenset[str], tuple[set[str], set[str]]] = {}
    for source in facts.sources:
        present = projected[source.identifier]
        if not present or present == entities:
            continue
        identity = _identifying_keys(source, present)
        own = facts.carried[source.identifier]
        if any(own[k] for k in identity):
            continue
        larger = [o for o in facts.sources if projected[o.identifier] > present]
        blocking = [
            frozenset().union(*(facts.carried[o.identifier][k] for k in identity))
            for o in larger
        ]
        if not blocking or not all(blocking):
            continue
        spans, witnesses = out.setdefault(present, (set(), set()))
        spans.update(*blocking)
        witnesses.add(source.identifier)
    return out


def _connected(
    entities: frozenset[str], facts: _ModelFacts
) -> dict[str, frozenset[str]]:
    """entity -> the entities some single source's rows carry beside it."""
    out: dict[str, frozenset[str]] = {e: frozenset({e}) for e in entities}
    for source in facts.sources:
        together = frozenset(facts.carried[source.identifier].keys() & entities)
        merged = together.union(*(out[e] for e in together))
        for entity in merged:
            out[entity] = merged
    return out


def _region_order(item: tuple[frozenset[str], object]) -> list[str]:
    return sorted(item[0])


def _null_rejected(conditions: list[BuildWhereClause]) -> set[str]:
    out: set[str] = set()
    for clause in conditions:
        out |= condition_proves_non_null(clause.conditional)
    return out


def _has_extension_license(environment: BuildEnvironment) -> bool:
    return any(
        ds.column_level_partial_addresses for ds in _build_datasources(environment)
    )


def build_keyspace(
    concept_attrs: dict[str, ConceptAttrs],
    mandatory_list: list[BuildConcept],
    environment: BuildEnvironment,
    conditions: list[BuildWhereClause],
) -> Keyspace:
    licensed = _has_extension_license(environment)
    canonical = _model_facts(environment).canonical if licensed else {}
    declared = {a.address: (a.purpose, a.keys) for a in concept_attrs.values()}
    keys_by_address = {
        address: frozenset(
            canonical.get(k, k) for k in _entity_keys(address, declared, environment)
        )
        for address in declared
    }
    entities: frozenset[str] = frozenset().union(*keys_by_address.values())
    output_entities: frozenset[str] = frozenset().union(
        *(keys_by_address.get(c.address, frozenset()) for c in mandatory_list)
    )
    base = Region(present=entities)
    if not licensed or not entities:
        return Keyspace(
            entities=entities,
            regions=(base,),
            keys_by_address=keys_by_address,
            output_entities=output_entities,
        )
    facts = _model_facts(environment)
    connected = _connected(entities, facts)
    rejected = _null_rejected(conditions)
    regions = [base]
    for present, (spans, witnesses) in sorted(
        _extension_regions(entities, facts).items(), key=_region_order
    ):
        # an entity no source relates to this region's rows is cross-joined
        # onto every row, so it is present here too
        reach: frozenset[str] = frozenset().union(*(connected[e] for e in present))
        full = present | (entities - reach)
        regions.append(
            Region(
                present=full,
                spans=frozenset(spans),
                sources=frozenset(witnesses),
                emptied_by=frozenset(
                    a
                    for a in rejected
                    if not keys_by_address.get(a, frozenset()) <= full
                ),
            )
        )
    return Keyspace(
        entities=entities,
        regions=tuple(regions),
        keys_by_address=keys_by_address,
        output_entities=output_entities,
    )
