"""A plan's row universe, computed once before grouping
(docs/keyspace_phase_plan.md).

A REGION is one kind of row the plan can return: the set of requested entity
keys present on it. Customers and orders, `orders.customer_id: ~customer_id`,
`select customer_id, status`: `{customer, order}` and `{customer}`.

Regions are generated by SOURCES. A row of a datasource carries every key the
datasource binds plus whatever a keyed lookup from those reaches, and each
carried key remembers the `~` bindings on its path (its CAUSE): an empty cause
means the rows span the key's whole domain. A source whose carried keys cover
only some of the requested entities witnesses a smaller region, which survives
only when every larger source reaches its rows through a `~`; those `~` keys
are the region's spans. Two sources carrying the same entities are one region
(`returns` binding `~order_id, ~item_id` beside `lines`), and there is no
`{user, product}` cell because no source carries exactly that.

Not modelled yet: a lookup through a source whose own grain is bound `~` (it
may miss, which makes the looked-up entity optional on the row), `complete
where` partitions (the union machinery owns them), and regions only a JOIN of
two facts can witness (the base region stands in for them).
"""

from __future__ import annotations

import dataclasses
from dataclasses import dataclass, field
from functools import partial
from weakref import ReferenceType, ref

from trilogy.core.enums import Derivation, Purpose
from trilogy.core.models.build import (
    BuildConcept,
    BuildDatasource,
    BuildWhereClause,
)
from trilogy.core.models.build_environment import BuildEnvironment
from trilogy.core.processing.condition_utility import condition_proves_non_null

from .models import ConceptAttrs, Keyspace, Region

# key -> the `~` bindings between a source's rows and that key's whole domain
Carried = dict[str, frozenset[str]]


@dataclass(frozen=True)
class _SourceFacts:
    identifier: str
    grain: frozenset[str]
    grain_is_partial: bool
    # bound address -> ({address} when bound `~`, else empty)
    bound: Carried


@dataclass
class _ModelFacts:
    """Binding facts of one environment, canonicalized over pseudonyms."""

    stamp: tuple[int, ...]
    canonical: dict[str, str]
    sources: tuple[_SourceFacts, ...]
    carried: dict[str, Carried]
    reach: dict[str, frozenset[str]] = field(default_factory=dict)

    def reach_of(self, key: str) -> frozenset[str]:
        """Addresses a keyed lookup arrives at from `key` alone."""
        cached = self.reach.get(key)
        if cached is None:
            seed = _SourceFacts("", frozenset(), False, {key: frozenset()})
            cached = self.reach[key] = frozenset(_carried(seed, self.sources))
        return cached


_FACTS_CACHE: dict[int, tuple[ReferenceType[BuildEnvironment], _ModelFacts]] = {}


def _evict_facts(key: int, _dead: ReferenceType) -> None:
    _FACTS_CACHE.pop(key, None)


def _build_datasources(environment: BuildEnvironment) -> list[BuildDatasource]:
    return [
        ds for ds in environment.datasources.values() if isinstance(ds, BuildDatasource)
    ]


def _canonical_addresses(environment: BuildEnvironment) -> dict[str, str]:
    """address -> the smallest spelling among it and its pseudonyms."""
    classes: dict[str, set[str]] = {}
    for key, concept in environment.concepts.items():
        merged = {key, concept.address, *concept.pseudonyms}
        for member in list(merged):
            merged |= classes.get(member, set())
        for member in merged:
            classes[member] = merged
    return {address: min(members) for address, members in classes.items()}


def _better(new: frozenset[str], old: frozenset[str] | None) -> bool:
    return old is None or len(new) < len(old)


def _source_facts(ds: BuildDatasource, canonical: dict[str, str]) -> _SourceFacts:
    partial_addresses = ds.column_level_partial_addresses
    bound: Carried = {}
    for column in ds.columns:
        address = column.concept.address
        key = canonical.get(address, address)
        # a merge respells the column onto its target; the `~` stays recorded
        # under the address it was authored on
        spelled = {address, column.origin_concept_address} & partial_addresses
        cause = frozenset(spelled)
        if _better(cause, bound.get(key)):
            bound[key] = cause
    grain = (
        frozenset()
        if ds.grain.abstract
        else frozenset(canonical.get(g, g) for g in ds.grain.components)
    )
    return _SourceFacts(
        identifier=ds.identifier,
        grain=grain,
        grain_is_partial=any(bound.get(g) for g in grain),
        bound=bound,
    )


def _carried(anchor: _SourceFacts, sources: tuple[_SourceFacts, ...]) -> Carried:
    """Every address a row of `anchor` has a value for, by keyed lookup.

    A lookup enters a source only through its whole grain, and never one whose
    grain is bound `~`: that source may hold no row for the anchor's key."""
    carried = dict(anchor.bound)
    changed = True
    while changed:
        changed = False
        for other in sources:
            if other is anchor or not other.grain or other.grain_is_partial:
                continue
            if not other.grain <= carried.keys():
                continue
            path: frozenset[str] = frozenset().union(*(carried[g] for g in other.grain))
            for address, cause in other.bound.items():
                if _better(path | cause, carried.get(address)):
                    carried[address] = path | cause
                    changed = True
    return carried


def _compute_facts(
    environment: BuildEnvironment, datasources: list[BuildDatasource]
) -> _ModelFacts:
    canonical = _canonical_addresses(environment)
    sources = tuple(_source_facts(ds, canonical) for ds in datasources)
    return _ModelFacts(
        # pin-heal and partition exclusion swap datasources before planning
        stamp=tuple(id(ds) for ds in datasources),
        canonical=canonical,
        sources=sources,
        carried={s.identifier: _carried(s, sources) for s in sources},
    )


def _model_facts(environment: BuildEnvironment) -> _ModelFacts:
    datasources = _build_datasources(environment)
    cache_key = id(environment)
    cached = _FACTS_CACHE.get(cache_key)
    if (
        cached is not None
        and cached[0]() is environment
        and cached[1].stamp == tuple(id(ds) for ds in datasources)
    ):
        return cached[1]
    facts = _compute_facts(environment, datasources)
    _FACTS_CACHE[cache_key] = (
        ref(environment, partial(_evict_facts, cache_key)),
        facts,
    )
    return facts


def _entity_keys(
    address: str,
    declared: dict[str, tuple[Purpose, frozenset[str]]],
    environment: BuildEnvironment,
    seen: frozenset[str] = frozenset(),
) -> frozenset[str]:
    """The entity keys a concept is a function of. A key is its own entity:
    the `keys` it carries are an FK-path addressing artifact (`customer_id`
    bound on `orders` lists `order_id`), not a determinant. Anything else lives
    on its keys' entities: an aggregate `by status` is keyed on the order."""
    known = declared.get(address)
    if known is None:
        concept = environment.concepts.get(address)
        if concept is None:
            return frozenset()
        known = (concept.purpose, frozenset(concept.keys or ()))
    purpose, keys = known
    if purpose == Purpose.KEY:
        return frozenset({address})
    seen = seen | {address}
    return frozenset().union(
        *(_entity_keys(k, declared, environment, seen) for k in keys if k not in seen)
    )


def _identifying_keys(source: _SourceFacts, present: frozenset[str]) -> frozenset[str]:
    """What identifies `source`'s rows once projected onto `present`: its grain
    when the projection keeps it, else every projected key."""
    if source.grain and source.grain <= present:
        return source.grain
    return present


def _witnesses(
    entities: frozenset[str], facts: _ModelFacts
) -> dict[frozenset[str], list[_SourceFacts]]:
    """present -> the sources whose rows carry exactly those entities."""
    out: dict[frozenset[str], list[_SourceFacts]] = {}
    for source in facts.sources:
        present = frozenset(facts.carried[source.identifier].keys() & entities)
        if present:
            out.setdefault(present, []).append(source)
    return out


def _identity_cause(
    source: _SourceFacts, identity: frozenset[str], facts: _ModelFacts
) -> frozenset[str]:
    carried = facts.carried[source.identifier]
    return frozenset().union(*(carried[k] for k in identity))


def _extension_spans(
    present: frozenset[str],
    witness: _SourceFacts,
    witnesses: dict[frozenset[str], list[_SourceFacts]],
    facts: _ModelFacts,
) -> frozenset[str]:
    """The `~` keys that keep `witness`'s rows out of every larger region;
    empty when it holds only some of its own, or a larger source holds them all."""
    identity = _identifying_keys(witness, present)
    if _identity_cause(witness, identity, facts):
        return frozenset()
    blocking = [
        _identity_cause(larger, identity, facts)
        for cell, sources in witnesses.items()
        if cell > present
        for larger in sources
    ]
    if not blocking or not all(blocking):
        return frozenset()
    return frozenset().union(*blocking)


def _completion_spans(
    present: frozenset[str],
    sources: list[_SourceFacts],
    requested_roots: frozenset[str],
    facts: _ModelFacts,
) -> frozenset[str]:
    """The `~` keys of a source the plan needs (it alone binds something
    requested) that holds only some of this region's rows, beside a source
    holding all of them: `returns` beside `lines`."""
    causes = {
        s.identifier: _identity_cause(s, _identifying_keys(s, present), facts)
        for s in sources
    }
    complete = [s for s in sources if not causes[s.identifier]]
    if not complete:
        return frozenset()
    held: frozenset[str] = frozenset().union(
        *(facts.carried[s.identifier].keys() for s in complete)
    )
    return frozenset().union(
        *(
            causes[s.identifier]
            for s in sources
            if causes[s.identifier] and (s.bound.keys() & requested_roots) - held
        )
    )


def _connected(
    entities: frozenset[str], facts: _ModelFacts
) -> dict[str, frozenset[str]]:
    """entity -> the entities some single source's rows carry beside it."""
    out: dict[str, frozenset[str]] = {e: frozenset({e}) for e in entities}
    for source in facts.sources:
        together = frozenset(facts.carried[source.identifier].keys() & entities)
        merged = together.union(*(out[e] for e in together))
        for entity in merged:
            out[entity] = merged
    return out


def _region_order(item: tuple[frozenset[str], object]) -> list[str]:
    return sorted(item[0])


def _null_rejected(conditions: list[BuildWhereClause]) -> set[str]:
    out: set[str] = set()
    for clause in conditions:
        out |= condition_proves_non_null(clause.conditional)
    return out


def _has_extension_license(datasources: list[BuildDatasource]) -> bool:
    return any(ds.column_level_partial_addresses for ds in datasources)


def build_keyspace(
    concept_attrs: dict[str, ConceptAttrs],
    mandatory_list: list[BuildConcept],
    environment: BuildEnvironment,
    conditions: list[BuildWhereClause],
    datasources: list[BuildDatasource] | None = None,
) -> Keyspace:
    """`datasources` overrides the environment's own (the audit replays a
    statement against its bindings as they stood before pin-heal)."""
    licensed = _has_extension_license(
        _build_datasources(environment) if datasources is None else datasources
    )
    if not licensed:
        facts = None
    elif datasources is None:
        facts = _model_facts(environment)
    else:
        facts = _compute_facts(environment, datasources)
    canonical = facts.canonical if facts else {}
    # an existence-only node is a semijoin's subselect, not a row of this plan
    declared = {
        a.address: (a.purpose, a.keys)
        for a in concept_attrs.values()
        if not a.existence_only
    }
    keys_by_address = {
        address: frozenset(
            canonical.get(k, k) for k in _entity_keys(address, declared, environment)
        )
        for address in declared
    }
    entities: frozenset[str] = frozenset().union(*keys_by_address.values())
    output_entities: frozenset[str] = frozenset().union(
        *(keys_by_address.get(c.address, frozenset()) for c in mandatory_list)
    )
    base = Region(present=entities)
    if facts is None or not entities:
        return Keyspace(
            entities=entities,
            regions=(base,),
            keys_by_address=keys_by_address,
            output_entities=output_entities,
        )
    requested_roots = frozenset(
        canonical.get(a.address, a.address)
        for a in concept_attrs.values()
        if a.derivation == Derivation.ROOT
    )
    witnesses = _witnesses(entities, facts)
    connected = _connected(entities, facts)
    rejected = _null_rejected(conditions)
    regions = [
        dataclasses.replace(
            base,
            completes=_completion_spans(
                entities, witnesses.get(entities, []), requested_roots, facts
            ),
        )
    ]
    for present, sources in sorted(witnesses.items(), key=_region_order):
        if present == entities:
            continue
        spans_by_witness = {
            s.identifier: _extension_spans(present, s, witnesses, facts)
            for s in sources
        }
        spans: frozenset[str] = frozenset().union(*spans_by_witness.values())
        if not spans:
            continue
        # an entity no source relates to this region's rows is cross-joined
        # onto every row, so it is present here too
        reach: frozenset[str] = frozenset().union(*(connected[e] for e in present))
        full = present | (entities - reach)
        regions.append(
            Region(
                present=full,
                spans=spans,
                completes=_completion_spans(present, sources, requested_roots, facts),
                sources=frozenset(i for i, found in spans_by_witness.items() if found),
                emptied_by=frozenset(
                    a
                    for a in rejected
                    if not keys_by_address.get(a, frozenset()) <= full
                ),
            )
        )
    in_play: frozenset[str] = frozenset().union(
        *(r.spans | r.completes for r in regions)
    )
    return Keyspace(
        entities=entities,
        regions=tuple(regions),
        keys_by_address=keys_by_address,
        output_entities=output_entities,
        outputs=tuple(c.address for c in mandatory_list),
        span_reach={
            span: frozenset(facts.reach_of(canonical.get(span, span)) & entities)
            for span in in_play
        },
    )
