"""A plan's row universe, computed once before grouping
(docs/keyspace_phase_plan.md).

A REGION is one kind of row the plan can return: the set of requested entity
keys present on it. Customers and orders, `orders.customer_id: ~customer_id`,
`select customer_id, status`: `{customer, order}` and `{customer}`.

Regions are generated by SOURCES. A row of a datasource carries every key the
datasource binds plus whatever a keyed lookup from those reaches, and each
carried key remembers the `~` bindings on its path (its CAUSE): an empty cause
means the rows span the key's whole domain. A source whose carried keys cover
only some of the requested entities witnesses a smaller region, which survives
only when every larger source reaches its rows through a `~`; those `~` keys
are the region's spans. Two sources carrying the same entities are one region
(`returns` binding `~order_id, ~item_id` beside `lines`), and there is no
`{user, product}` cell because no source carries exactly that.

A region also records whose rows it is (`witnesses`) and its `completions`: a
source holding only SOME of its rows beside sources holding the rest. No entity
is absent on the rows such a source lacks, so they are not a region of their
own, but a WHERE null-rejecting what only that source supplies still removes
them. `Keyspace.binding_is_complete` is pin-heal's question, asked of both.

A ROWSET the plan reads is a source too (`RowsetWitness`): its rows are its
body's regions, spelled in the handles that expose them. `select order_number
as o, item_sk as sk` holds a row for the item no sale references, with `o`
absent on it, so the plan reading `s.o, s.sk` has the same two regions the body
had. A body region the plan above holds the rows of (`owned_spans`) is not part
of a body plan built for that consumer: the body then reads the solid rows.

Not modelled yet: a lookup through a source whose own grain is bound `~` (it
may miss, which makes the looked-up entity optional on the row), `complete
where` partitions as regions (the union machinery owns them; they are read
only to know that mutually exclusive slices are not each other's missing
rows), and regions only a JOIN of two facts can witness (the base region
stands in for them).
"""

from __future__ import annotations

import dataclasses
from dataclasses import dataclass, field
from functools import partial
from weakref import ReferenceType, ref

from trilogy.core.enums import Derivation, Purpose
from trilogy.core.models.build import (
    BuildAggregateWrapper,
    BuildConcept,
    BuildDatasource,
    BuildRowsetItem,
    BuildWhereClause,
)
from trilogy.core.models.build_environment import BuildEnvironment
from trilogy.core.processing.condition_utility import gather_non_null_proofs

from .models import Completion, ConceptAttrs, Keyspace, Region

_Declared = tuple[Purpose, Derivation, frozenset[str]]

# derivations that GENERATE their key's values, so the concept is that key's
# whole domain rather than a function or a subset of some source's rows
_DOMAIN_GENERATORS = frozenset({Derivation.UNNEST, Derivation.CONSTANT})

# key -> the `~` bindings between a source's rows and that key's whole domain
Carried = dict[str, frozenset[str]]


@dataclass(frozen=True)
class _SourceFacts:
    identifier: str
    grain: frozenset[str]
    grain_is_partial: bool
    # bound address -> ({address} when bound `~`, else empty)
    bound: Carried


@dataclass
class _ModelFacts:
    """Binding facts of one environment, canonicalized over pseudonyms."""

    stamp: tuple[int, ...]
    canonical: dict[str, str]
    sources: tuple[_SourceFacts, ...]
    carried: dict[str, Carried]
    # every spelling of an address that is part of some source's row identity
    identifying: frozenset[str] = frozenset()
    reach: dict[str, frozenset[str]] = field(default_factory=dict)

    def reach_of(self, key: str) -> frozenset[str]:
        """Addresses a keyed lookup arrives at from `key` alone."""
        cached = self.reach.get(key)
        if cached is None:
            seed = _SourceFacts("", frozenset(), False, {key: frozenset()})
            cached = self.reach[key] = frozenset(_carried(seed, self.sources))
        return cached


@dataclass(frozen=True)
class RowsetRegion:
    """One live region of a rowset body, in the handles that expose it:
    `present` the key handles on it, `bound` every handle defined on it,
    `spans` the handles spelling the body region's spans (`body_spans`)."""

    present: frozenset[str]
    bound: frozenset[str]
    spans: frozenset[str]
    body_spans: frozenset[str]


@dataclass(frozen=True)
class RowsetWitness:
    """A rowset the plan reads, as a source of it (`rowset_witness`)."""

    name: str
    regions: tuple[RowsetRegion, ...]
    # handle -> the key handles it is a function of, within this rowset
    entity_handles: dict[str, frozenset[str]] = field(default_factory=dict)

    @property
    def licensed(self) -> bool:
        return any(r.spans for r in self.regions)

    def body_spans_of(self, spans: frozenset[str]) -> frozenset[str]:
        """The body's spelling of every region `spans` covers."""
        return frozenset().union(
            *(r.body_spans for r in self.regions if r.spans and r.spans <= spans)
        )


def rowset_witness(
    name: str,
    handles: list[BuildConcept],
    body: Keyspace,
    body_environment: BuildEnvironment,
) -> RowsetWitness:
    """The body's live regions respelled in the rowset's handles. A region
    whose span no handle spells is one the reader cannot name, so it is not
    a region of the reader's plan (its rows are read as the base region's,
    as before)."""
    canonical = _model_facts(body_environment).canonical
    contents = {
        h.address: canonical.get(h.lineage.content.address, h.lineage.content.address)
        for h in handles
        if isinstance(h.lineage, BuildRowsetItem)
    }
    keys = {
        handle: body.keys_by_address.get(content)
        or frozenset(
            canonical.get(k, k) for k in entity_keys(content, body_environment)
        )
        for handle, content in contents.items()
    }
    entity_handles = {
        handle: frozenset(h for h, c in contents.items() if c in keys[handle])
        for handle in contents
    }
    regions: list[RowsetRegion] = []
    for region in body.live_regions:
        body_spans = {canonical.get(s, s) for s in region.spans}
        spans = frozenset(h for h, c in contents.items() if c in body_spans)
        if not body_spans <= set(contents.values()):
            continue
        regions.append(
            RowsetRegion(
                present=frozenset(
                    h for h, c in contents.items() if c in region.present
                ),
                bound=frozenset(h for h, k in keys.items() if k <= region.present),
                spans=spans,
                body_spans=region.spans,
            )
        )
    return RowsetWitness(
        name=name, regions=tuple(regions), entity_handles=entity_handles
    )


def _rowset_sources(witnesses: tuple[RowsetWitness, ...]) -> tuple[_SourceFacts, ...]:
    """One source per witnessed region. A handle is bound `~` when a smaller
    region of the same body spells its key as a span: the larger rows reach
    the smaller region's rows through it, as `sales` reaches the items no sale
    references through `~item_sk`."""
    out: list[_SourceFacts] = []
    for witness in witnesses:
        for region in witness.regions:
            partial = frozenset().union(
                *(r.spans for r in witness.regions if r.present < region.present)
            )
            bound: Carried = {
                handle: witness.entity_handles.get(handle, frozenset()) & partial
                for handle in region.bound
            }
            out.append(
                _SourceFacts(
                    identifier=f"rowset:{witness.name}:{'|'.join(sorted(region.present))}",
                    grain=region.present,
                    grain_is_partial=any(bound.get(g) for g in region.present),
                    bound=bound,
                )
            )
    return tuple(out)


_FACTS_CACHE: dict[int, tuple[ReferenceType[BuildEnvironment], _ModelFacts]] = {}


def _evict_facts(key: int, _dead: ReferenceType) -> None:
    _FACTS_CACHE.pop(key, None)


def build_datasources(environment: BuildEnvironment) -> list[BuildDatasource]:
    return [
        ds for ds in environment.datasources.values() if isinstance(ds, BuildDatasource)
    ]


def _canonical_addresses(environment: BuildEnvironment) -> dict[str, str]:
    """address -> the smallest spelling among it and its pseudonyms."""
    classes: dict[str, set[str]] = {}
    for key, concept in environment.concepts.items():
        merged = {key, concept.address, *concept.pseudonyms}
        for member in list(merged):
            merged |= classes.get(member, set())
        for member in merged:
            classes[member] = merged
    return {address: min(members) for address, members in classes.items()}


def _better(new: frozenset[str], old: frozenset[str] | None) -> bool:
    return old is None or len(new) < len(old)


def _fewest_keys_first(item: tuple[str, frozenset[str]]) -> tuple[int, str]:
    return len(item[1]), item[0]


def _row_identities(datasources: list[BuildDatasource]) -> dict[str, frozenset[str]]:
    """What identifies a row of each source: its declared grain, else its KEY
    columns less the ones that identify ANOTHER source on their own, which it
    holds as foreign keys (`customers` binding `id, nation.id` with no grain is
    one row per `id` once `nation` is known to be one row per `nation.id`)."""
    out = {
        ds.identifier: frozenset(ds.grain.components)
        for ds in datasources
        if not ds.grain.abstract
    }
    pending = {
        ds.identifier: frozenset(
            c.concept.address for c in ds.columns if c.concept.purpose == Purpose.KEY
        )
        for ds in datasources
        if ds.grain.abstract
    }
    sole = {next(iter(grain)) for grain in out.values() if len(grain) == 1}
    settled = True
    while settled:
        settled = False
        for identifier, keys in sorted(pending.items(), key=_fewest_keys_first):
            own = keys - sole if len(keys) > 1 else keys
            if len(own) == 1:
                out[identifier] = own
                sole |= own
                del pending[identifier]
                settled = True
                break
    return {**out, **pending}


def _source_facts(
    ds: BuildDatasource, canonical: dict[str, str], identity: frozenset[str]
) -> _SourceFacts:
    partial_addresses = ds.column_level_partial_addresses
    bound: Carried = {}
    for column in ds.columns:
        address = column.concept.address
        key = canonical.get(address, address)
        # a merge respells the column onto its target; the `~` stays recorded
        # under the address it was authored on
        spelled = {address, column.origin_concept_address} & partial_addresses
        cause = frozenset(spelled)
        if _better(cause, bound.get(key)):
            bound[key] = cause
    grain = frozenset(canonical.get(g, g) for g in identity)
    return _SourceFacts(
        identifier=ds.identifier,
        grain=grain,
        grain_is_partial=any(bound.get(g) for g in grain),
        bound=bound,
    )


def _generated_domains(
    environment: BuildEnvironment,
    canonical: dict[str, str],
    bound: tuple[_SourceFacts, ...],
) -> tuple[_SourceFacts, ...]:
    """A key some source binds `~` whose complete side is a derivation, not a
    table: `merge orid into ~orid_2` with `orid_2 <- unnest([1, 2, 3])`."""
    partial_keys = {key for s in bound for key, cause in s.bound.items() if cause}
    out: dict[str, _SourceFacts] = {}
    for concept in environment.concepts.values():
        key = canonical.get(concept.address, concept.address)
        if (
            concept.purpose == Purpose.KEY
            and concept.derivation in _DOMAIN_GENERATORS
            and key in partial_keys
        ):
            out[concept.address] = _SourceFacts(
                identifier=f"generated:{concept.address}",
                grain=frozenset({key}),
                grain_is_partial=False,
                bound={key: frozenset()},
            )
    return tuple(out[address] for address in sorted(out))


def _carried(anchor: _SourceFacts, sources: tuple[_SourceFacts, ...]) -> Carried:
    """Every address a row of `anchor` has a value for, by keyed lookup.

    A lookup enters a source only through its whole grain, and never one whose
    grain is bound `~`: that source may hold no row for the anchor's key."""
    carried = dict(anchor.bound)
    changed = True
    while changed:
        changed = False
        for other in sources:
            if other is anchor or not other.grain or other.grain_is_partial:
                continue
            if not other.grain <= carried.keys():
                continue
            path: frozenset[str] = frozenset().union(*(carried[g] for g in other.grain))
            for address, cause in other.bound.items():
                if _better(path | cause, carried.get(address)):
                    carried[address] = path | cause
                    changed = True
    return carried


def _compute_facts(
    environment: BuildEnvironment,
    datasources: list[BuildDatasource],
    rowsets: tuple[_SourceFacts, ...] = (),
) -> _ModelFacts:
    canonical = _canonical_addresses(environment)
    identities = _row_identities(datasources)
    bound = tuple(
        _source_facts(ds, canonical, identities[ds.identifier]) for ds in datasources
    )
    sources = bound + _generated_domains(environment, canonical, bound) + rowsets
    return _ModelFacts(
        # pin-heal and partition exclusion swap datasources before planning
        stamp=tuple(id(ds) for ds in datasources),
        canonical=canonical,
        sources=sources,
        carried={s.identifier: _carried(s, sources) for s in sources},
        identifying=frozenset(
            address
            for address, key in canonical.items()
            if any(key in s.grain for s in sources)
        ),
    )


def _model_facts(environment: BuildEnvironment) -> _ModelFacts:
    datasources = build_datasources(environment)
    cache_key = id(environment)
    cached = _FACTS_CACHE.get(cache_key)
    if (
        cached is not None
        and cached[0]() is environment
        and cached[1].stamp == tuple(id(ds) for ds in datasources)
    ):
        return cached[1]
    facts = _compute_facts(environment, datasources)
    _FACTS_CACHE[cache_key] = (
        ref(environment, partial(_evict_facts, cache_key)),
        facts,
    )
    return facts


def _entity_keys(
    address: str,
    declared: dict[str, _Declared],
    identifying: frozenset[str],
    environment: BuildEnvironment,
    seen: frozenset[str] = frozenset(),
) -> frozenset[str]:
    """The entity keys a concept is a function of. A key is its own entity:
    the `keys` it carries are an FK-path addressing artifact (`customer_id`
    bound on `orders` lists `order_id`), not a determinant. So is a property
    that identifies the rows of some source (`region`, the grain of
    `region_dim`). Anything else lives on its keys' entities: an aggregate `by
    status` is keyed on the order. A BASIC is a function of what it READS
    (`orbit_code <- upper(category)`), not of its declared keys: over an
    aggregate those still name the aggregate's argument (`coalesce(sum(amount),
    0)` lists `order_id`), which the aggregate is evaluated OVER, not on.

    A rowset key stays its OWN entity: the rowset is a row source, and stores
    no order references are not rows of `select even_orders.store_id`."""
    known = declared.get(address)
    if known is None:
        concept = environment.concepts.get(address)
        if concept is None:
            return frozenset()
        known = (concept.purpose, concept.derivation, frozenset(concept.keys or ()))
    purpose, derivation, keys = known
    own_entity = purpose == Purpose.KEY and derivation != Derivation.BASIC
    if own_entity or address in identifying:
        return frozenset({address})
    if derivation == Derivation.BASIC:
        keys = _read_addresses(address, environment) or keys
    elif derivation == Derivation.AGGREGATE and not keys:
        # a ROLLUP aggregate declares no keys; it is still evaluated by its `by`
        keys = _grouping_addresses(address, environment)
    seen = seen | {address}
    return frozenset().union(
        *(
            _entity_keys(k, declared, identifying, environment, seen)
            for k in keys
            if k not in seen
        )
    )


def entity_keys(address: str, environment: BuildEnvironment) -> frozenset[str]:
    """The entity keys `address` is a function of (`_entity_keys`)."""
    identifying = _model_facts(environment).identifying
    return _entity_keys(address, {}, identifying, environment)


def _read_addresses(address: str, environment: BuildEnvironment) -> frozenset[str]:
    concept = environment.concepts.get(address)
    if concept is None or concept.lineage is None:
        return frozenset()
    return frozenset(arg.address for arg in concept.lineage.concept_arguments)


def _grouping_addresses(address: str, environment: BuildEnvironment) -> frozenset[str]:
    concept = environment.concepts.get(address)
    if concept is None or not isinstance(concept.lineage, BuildAggregateWrapper):
        return frozenset()
    return frozenset(b.address for b in concept.lineage.by)


def _identifying_keys(source: _SourceFacts, present: frozenset[str]) -> frozenset[str]:
    """What identifies `source`'s rows once projected onto `present`: its grain
    when the projection keeps it, else every projected key."""
    if source.grain and source.grain <= present:
        return source.grain
    return present


def _witnesses(
    entities: frozenset[str], facts: _ModelFacts
) -> dict[frozenset[str], list[_SourceFacts]]:
    """present -> the sources whose rows carry exactly those entities."""
    out: dict[frozenset[str], list[_SourceFacts]] = {}
    for source in facts.sources:
        present = frozenset(facts.carried[source.identifier].keys() & entities)
        if present:
            out.setdefault(present, []).append(source)
    return out


def _identity_cause(
    source: _SourceFacts, identity: frozenset[str], facts: _ModelFacts
) -> frozenset[str]:
    carried = facts.carried[source.identifier]
    return frozenset().union(*(carried[k] for k in identity))


def _extension_spans(
    present: frozenset[str],
    witness: _SourceFacts,
    witnesses: dict[frozenset[str], list[_SourceFacts]],
    facts: _ModelFacts,
) -> frozenset[str]:
    """The `~` keys that keep `witness`'s rows out of every larger region;
    empty when it holds only some of its own, or a larger source holds them all."""
    identity = _identifying_keys(witness, present)
    if _identity_cause(witness, identity, facts):
        return frozenset()
    blocking = [
        _identity_cause(larger, identity, facts)
        for cell, sources in witnesses.items()
        if cell > present
        for larger in sources
    ]
    if not blocking or not all(blocking):
        return frozenset()
    return frozenset().union(*blocking)


def _bridges(
    source: _SourceFacts,
    present: frozenset[str],
    entities: frozenset[str],
    facts: _ModelFacts,
) -> bool:
    """`source` shares a column with a source carrying an entity outside
    `present`: the fan-out join that relates this region to the rest of the
    statement (`stages` between `engines` and the launches)."""
    return any(
        other is not source
        and source.bound.keys() & other.bound.keys()
        and (facts.carried[other.identifier].keys() & entities) - present
        for other in facts.sources
    )


def _completions(
    present: frozenset[str],
    sources: list[_SourceFacts],
    requested_roots: frozenset[str],
    entities: frozenset[str],
    rejected: frozenset[str],
    facts: _ModelFacts,
) -> tuple[frozenset[str], tuple[Completion, ...]]:
    """The `~` keys of a source the plan needs that holds only some of this
    region's rows, beside a source holding all of them: `returns` beside
    `lines`. Needed means it alone binds something requested, or it is what
    joins the region to the rest of the statement."""
    causes = {
        s.identifier: _identity_cause(s, _identifying_keys(s, present), facts)
        for s in sources
    }
    complete = [s for s in sources if not causes[s.identifier]]
    if not complete:
        # two partial sources have no defined relationship: the full set is a
        # complete source (or a `complete where` slice the union machinery
        # stacks), never the partial ones completing each other
        return frozenset(), ()
    held: frozenset[str] = frozenset().union(
        *(facts.carried[s.identifier].keys() for s in complete)
    )
    found = tuple(
        Completion(
            source=s.identifier,
            spans=causes[s.identifier],
            # NULL on every row of the region this source has no match for
            emptied_by=rejected & (facts.carried[s.identifier].keys() - held),
        )
        for s in sources
        if causes[s.identifier]
        and (
            (s.bound.keys() & requested_roots) - held
            or _bridges(s, present, entities, facts)
        )
    )
    return frozenset().union(*(c.spans for c in found)), found


def _connected(
    entities: frozenset[str], facts: _ModelFacts
) -> dict[str, frozenset[str]]:
    """entity -> the entities of its model component: sources sharing a column
    can be joined, so their entities meet on some row."""
    components: list[tuple[set[str], set[str]]] = []
    for source in facts.sources:
        columns = set(facts.carried[source.identifier])
        found = columns & entities
        for other in [c for c in components if c[0] & columns]:
            components.remove(other)
            columns |= other[0]
            found |= other[1]
        components.append((columns, found))
    out = {e: frozenset({e}) for e in entities}
    for _, found in components:
        for entity in found:
            out[entity] = frozenset(found)
    return out


def _region_order(item: tuple[frozenset[str], object]) -> list[str]:
    return sorted(item[0])


def null_rejected(conditions: list[BuildWhereClause]) -> set[str]:
    """What the statement's WHERE forces non-null, BETWEEN included: an absent
    concept is NULL however it renders, so every atom that rejects NULL empties
    the region it is absent on."""
    out: set[str] = set()
    for clause in conditions:
        out |= gather_non_null_proofs(clause.conditional)
    return out


def _has_extension_license(datasources: list[BuildDatasource]) -> bool:
    return any(ds.column_level_partial_addresses for ds in datasources)


def build_keyspace(
    concept_attrs: dict[str, ConceptAttrs],
    mandatory_list: list[BuildConcept],
    environment: BuildEnvironment,
    conditions: list[BuildWhereClause],
    datasources: list[BuildDatasource] | None = None,
    rowset_witnesses: tuple[RowsetWitness, ...] = (),
) -> Keyspace:
    """`datasources` overrides the environment's (uncached): the heal audit
    builds over the bindings as authored after pin-heal has rewritten them.
    `rowset_witnesses` are the rowsets the plan reads, sources beside them.

    The facts are read whether or not any `~` survives (pin-heal may have
    dropped the last one): an entity is spelled by the same canonical
    address either way, and a plan's keys are compared across plans."""
    rowsets = _rowset_sources(rowset_witnesses)
    if datasources is None and not rowsets:
        datasources = build_datasources(environment)
        facts = _model_facts(environment)
    else:
        datasources = (
            build_datasources(environment) if datasources is None else datasources
        )
        facts = _compute_facts(environment, datasources, rowsets)
    licensed = _has_extension_license(datasources) or any(
        w.licensed for w in rowset_witnesses
    )
    canonical = facts.canonical
    identifying = facts.identifying
    # an existence-only node is a semijoin's subselect, not a row of this plan
    declared = {
        a.address: (a.purpose, a.derivation, a.keys)
        for a in concept_attrs.values()
        if not a.existence_only
    }
    keys_by_address = {
        address: frozenset(
            canonical.get(k, k)
            for k in _entity_keys(address, declared, identifying, environment)
        )
        for address in declared
    }
    entities: frozenset[str] = frozenset().union(*keys_by_address.values())
    base = Region(present=entities)
    if not licensed or not entities:
        return Keyspace(
            entities=entities,
            regions=(base,),
            keys_by_address=keys_by_address,
        )
    requested_roots = frozenset(
        canonical.get(a.address, a.address)
        for a in concept_attrs.values()
        if a.derivation == Derivation.ROOT
    )
    witnesses = _witnesses(entities, facts)
    connected = _connected(entities, facts)
    rejected = null_rejected(conditions)
    rejected_roots = frozenset(canonical.get(a, a) for a in rejected)
    base_sources = witnesses.get(entities, [])
    base_completes, base_completions = _completions(
        entities, base_sources, requested_roots, entities, rejected_roots, facts
    )
    regions = [
        dataclasses.replace(
            base,
            completes=base_completes,
            witnesses=frozenset(s.identifier for s in base_sources),
            completions=base_completions,
        )
    ]
    for present, sources in sorted(witnesses.items(), key=_region_order):
        if present == entities:
            continue
        spans_by_witness = {
            s.identifier: _extension_spans(present, s, witnesses, facts)
            for s in sources
        }
        completes, completions = _completions(
            present, sources, requested_roots, entities, rejected_roots, facts
        )
        # kept out of the larger regions by a lookup's `~`, or by a bridge's
        spans: frozenset[str] = completes.union(*spans_by_witness.values())
        if not spans:
            continue
        # an entity no source relates to this region's rows is cross-joined
        # onto every row, so it is present here too
        reach: frozenset[str] = frozenset().union(*(connected[e] for e in present))
        full = present | (entities - reach)
        regions.append(
            Region(
                present=full,
                spans=spans,
                completes=completes,
                sources=frozenset(i for i, found in spans_by_witness.items() if found),
                witnesses=frozenset(s.identifier for s in sources),
                completions=completions,
                emptied_by=frozenset(
                    a
                    for a in rejected
                    if not keys_by_address.get(a, frozenset()) <= full
                ),
            )
        )
    in_play: frozenset[str] = frozenset().union(
        *(r.spans | r.completes for r in regions)
    )
    return Keyspace(
        entities=entities,
        regions=tuple(regions),
        keys_by_address=keys_by_address,
        outputs=tuple(c.address for c in mandatory_list),
        span_reach={
            span: frozenset(facts.reach_of(canonical.get(span, span)) & entities)
            for span in in_play
        },
    )
