
WITH 
quizzical as (SELECT
    EXTRACT(YEAR from team_games_sr.`scheduled_date`) as `scheduled_date_year`,
    team_games_sr.`game_id` as `id`,
    team_games_sr.`points_game` as `points_game`,
    team_games_sr.`team_id` as `team_id`,
    team_games_sr.`team_name` as `team_name`,
    team_games_sr.`team_rank` as `team_rank`
FROM
    (
SELECT
  game_id,
  h_id as team_id,
  TRUE as is_home,
  season,
  status,
  coverage,
  scheduled_date,
  gametime,
  a_id as opponent_team_id,
  a_name as opponent_name,
  a_market as opponent_market,
  a_alias as opponent_alias,
  a_points as opponent_points,
  h_name as team_name,
  h_market as team_market,
  h_alias as team_alias,
  h_league_id as team_league_id,
  h_league_name as team_league_name,
  h_league_alias as team_league_alias,
  h_conf_id as team_conf_id,
  h_conf_name as team_conf_name,
  h_conf_alias as team_conf_alias,
  h_division_id as team_division_id,
  h_division_name as team_division_name,
  h_division_alias as team_division_alias,
  h_logo_large as team_logo_large,
  h_logo_medium as team_logo_medium,
  h_logo_small as team_logo_small,
  h_points_game as points_game,
  h_rank as team_rank,
  h_minutes as team_minutes,
  h_field_goals_made as field_goals_made,
  h_field_goals_att as field_goals_att,
  h_field_goals_pct as field_goals_pct,
  h_three_points_att as three_points_att,
  h_three_points_made as three_points_made,
  h_three_points_pct as three_points_pct,
  h_two_points_made as two_points_made,
  h_two_points_att as two_points_att,
  h_two_points_pct as two_points_pct,
  h_blocked_att as blocked_att,
  h_free_throws_made as free_throws_made,
  h_free_throws_att as free_throws_att,
  h_free_throws_pct as free_throws_pct,
  h_offensive_rebounds as offensive_rebounds,
  h_defensive_rebounds as defensive_rebounds,
  h_rebounds as rebounds,
  h_assists as assists,
  h_turnovers as turnovers,
  h_steals as steals,
  h_blocks as blocks,
  h_assists_turnover_ratio as assists_turnover_ratio,
  h_personal_fouls as personal_fouls,
  h_ejections as ejections,
  h_foulouts as foulouts,
  h_points as points,
  h_fast_break_pts as fast_break_pts,
  h_second_chance_pts as second_chance_pts,
  h_team_turnovers as team_turnovers,
  h_points_off_turnovers as points_off_turnovers,
  h_team_rebounds as team_rebounds,
  h_flagrant_fouls as flagrant_fouls,
  h_player_tech_fouls as player_tech_fouls,
  h_team_tech_fouls as team_tech_fouls,
  h_coach_tech_fouls as coach_tech_fouls,
  conference_game,
  tournament,
  tournament_type,
  tournament_round,
  tournament_game_no,
  attendance,
  lead_changes,
  times_tied,
  periods,
  neutral_site,
  possession_arrow,
  venue_id,
  venue_city,
  venue_state,
  venue_address,
  venue_zip,
  venue_country,
  venue_name,
  venue_capacity,
  created
FROM `bigquery-public-data.ncaa_basketball.mbb_games_sr`
UNION ALL
SELECT
  game_id,
  a_id as team_id,
  FALSE as is_home,
  season,
  status,
  coverage,
  scheduled_date,
  gametime,
  h_id as opponent_team_id,
  h_name as opponent_name,
  h_market as opponent_market,
  h_alias as opponent_alias,
  h_points as opponent_points,
  a_name as team_name,
  a_market as team_market,
  a_alias as team_alias,
  a_league_id as team_league_id,
  a_league_name as team_league_name,
  a_league_alias as team_league_alias,
  a_conf_id as team_conf_id,
  a_conf_name as team_conf_name,
  a_conf_alias as team_conf_alias,
  a_division_id as team_division_id,
  a_division_name as team_division_name,
  a_division_alias as team_division_alias,
  a_logo_large as team_logo_large,
  a_logo_medium as team_logo_medium,
  a_logo_small as team_logo_small,
  a_points_game as points_game,
  a_rank as team_rank,
  a_minutes as team_minutes,
  a_field_goals_made as field_goals_made,
  a_field_goals_att as field_goals_att,
  a_field_goals_pct as field_goals_pct,
  a_three_points_att as three_points_att,
  a_three_points_made as three_points_made,
  a_three_points_pct as three_points_pct,
  a_two_points_made as two_points_made,
  a_two_points_att as two_points_att,
  a_two_points_pct as two_points_pct,
  a_blocked_att as blocked_att,
  a_free_throws_made as free_throws_made,
  a_free_throws_att as free_throws_att,
  a_free_throws_pct as free_throws_pct,
  a_offensive_rebounds as offensive_rebounds,
  a_defensive_rebounds as defensive_rebounds,
  a_rebounds as rebounds,
  a_assists as assists,
  a_turnovers as turnovers,
  a_steals as steals,
  a_blocks as blocks,
  a_assists_turnover_ratio as assists_turnover_ratio,
  a_personal_fouls as personal_fouls,
  a_ejections as ejections,
  a_foulouts as foulouts,
  a_points as points,
  a_fast_break_pts as fast_break_pts,
  a_second_chance_pts as second_chance_pts,
  a_team_turnovers as team_turnovers,
  a_points_off_turnovers as points_off_turnovers,
  a_team_rebounds as team_rebounds,
  a_flagrant_fouls as flagrant_fouls,
  a_player_tech_fouls as player_tech_fouls,
  a_team_tech_fouls as team_tech_fouls,
  a_coach_tech_fouls as coach_tech_fouls,
  conference_game,
  tournament,
  tournament_type,
  tournament_round,
  tournament_game_no,
  attendance,
  lead_changes,
  times_tied,
  periods,
  neutral_site,
  possession_arrow,
  venue_id,
  venue_city,
  venue_state,
  venue_address,
  venue_zip,
  venue_country,
  venue_name,
  venue_capacity,
  created
FROM `bigquery-public-data.ncaa_basketball.mbb_games_sr`
) as team_games_sr
WHERE
    team_games_sr.`team_league_name` = 'NCAA MEN'
)SELECT
    quizzical.`scheduled_date_year` as `scheduled_date_year`,
    quizzical.`team_name` as `team_name`,
    sum(quizzical.`points_game`) as `total_points`,
    quizzical.`team_rank` as `team_rank`
FROM
    quizzical
GROUP BY 
    quizzical.`scheduled_date_year`,
    quizzical.`team_name`,
    quizzical.`team_rank`
ORDER BY 
    quizzical.`scheduled_date_year` asc,
    quizzical.`team_rank` asc
LIMIT 10000