"""Display helpers for prettier CLI output with configurable Rich support."""

# Re-export everything from the focused submodules for backward compatibility.
from trilogy.scripts.display_core import (  # noqa: F401
    COL_CYAN,
    COL_DIM,
    COL_GREEN,
    COL_WHITE,
    FETCH_LIMIT,
    HEADER_BLUE,
    HEADER_GREEN,
    HEADER_YELLOW,
    RICH_AVAILABLE,
    STYLE_ERROR,
    STYLE_HEADER,
    STYLE_INFO,
    STYLE_SUCCESS,
    STYLE_WARNING,
    RichModeContext,
    SetRichMode,
    _DummyContext,
    _FdStderrCapture,
    _print_styled,
    console,
    format_duration,
    is_rich_available,
    print_error,
    print_header,
    print_info,
    print_success,
    print_warning,
    set_rich_mode,
    with_status,
)
from trilogy.scripts.display_execution import (  # noqa: F401
    _print_fallback_table,
    _print_rich_table,
    create_progress_context,
    print_chart_terminal,
    print_results_table,
    show_debug_mode,
    show_environment_params,
    show_execution_info,
    show_execution_start,
    show_execution_summary,
    show_formatting_result,
    show_statement_result,
    show_statement_type,
)
from trilogy.scripts.display_models import (  # noqa: F401
    ManagedDataGroup,
    ResultSet,
    StaleDataSourceEntry,
)
from trilogy.scripts.display_parallel import (  # noqa: F401
    ParallelProgressTracker,
    _make_futures_context_getter,
    show_execution_plan,
    show_parallel_execution_start,
    show_parallel_execution_summary,
    show_script_result,
)
from trilogy.scripts.display_refresh import (  # noqa: F401
    _common_prefix,
    _ProbeProgressContext,
    probe_progress,
    root_probe_progress,
    show_asset_status_summary,
    show_dry_run_queries,
    show_grouped_refresh_assets,
    show_managed_asset_list,
    show_refresh_plan,
    show_root_concepts,
    show_root_probe_breakdown,
    show_stale_assets,
    show_watermarks,
)
